include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true

analyzer:
  plugins:
    - custom_lint

  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/generated/**

  errors:
    invalid_annotation_target: ignore

custom_lint:
  enable_all_lint_rules: true
