name: shorebird_demo
description: 'A new Flutter project.'

publish_to: 'none'

version: 4.0.0+10001

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  freezed_annotation: 2.4.4

  gap: 3.0.1
  json_annotation: 4.9.0

  just_audio: 0.9.42

  shared_preferences: 2.3.3

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3
  flutter_lints: 4.0.0
  freezed: 2.5.7
  json_serializable: 6.9.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/audios/
    - assets/images/
    - shorebird.yaml

flutter_intl:
  enabled: true
